#
# Native Quarkus CircleCI configuration file
#
version: 2.1
orbs:
  openjdk-install: cloudesire/openjdk-install@1.2.3
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecs: circleci/aws-ecs@0.0.10

commands:
  restore_repo:
    description: "Restore repo from cache"
    steps:
      - restore_cache:
          keys:
            - cache-repo
  restore_image_file:
    description: "Restore docker image file from cache"
    steps:
      - restore_cache:
          keys:
            - native-build-binary
executors:
  linux-executor:
    machine: true
    resource_class: medium
    working_directory: ~/repo
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      TERM: dumb
      # Set the GRAALVM_HOME env variable to the location where we will be installing GraalVM
      GRAALVM_HOME: /home/circleci/repo/.graalvm
  graalvm-java11:
    docker:
      - image: oracle/graalvm-ce:20.2.0-java11

jobs:
  build:
    executor: graalvm-java11
    steps:
      - restore_repo

      # Checkout the source code
      # ########################
      - checkout
      - save_cache:
          paths:
            - .
          key: cache-repo

      # Restore any files we may have cached
      # ########################
      - restore_cache:
          keys:
            - gradle-dependencies-native
      # Cache the maven dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-native

      # Install GraalVM and native-image, needed for a native Quarkus build
      # ########################
      - run:
          name: Build (jar)
          command: ./gradlew quarkusBuild
      - store_artifacts:
          path: build/libs/lcm-sayu-1.0.0-SNAPSHOT.jar

  native:
    executor: linux-executor
    steps:
      - restore_repo

      - openjdk-install/openjdk:
          version: 11

      # Restore any files we may have cached
      # ########################
      - restore_cache:
          keys:
            - gradle-dependencies-native
      # Cache the maven dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-native

      # Install GraalVM and native-image, needed for a native Quarkus build
      # ########################
      - run:
          name: Install GraalVM
          command: curl https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz -O -J -L && tar xfz graalvm-ce-java11-linux-amd64-20.2.0.tar.gz && mv graalvm-ce-java11-20.2.0 .graalvm && rm graalvm-ce-java11-linux-amd64-20.2.0.tar.gz
      - run:
          name: Install native-image
          command: $GRAALVM_HOME/bin/gu install native-image

      # Perform a native Quarkus build and verify
      # ########################
      - run:
          name: Build (Native)
          command: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.additional-build-args=--static
          no_output_timeout: 15m

      - save_cache:
          paths:
            - ~/build/lcm-sayu-1.0.0-SNAPSHOT-runner
          key: native-build-binary

      - store_artifacts:
          path: build/lcm-sayu-1.0.0-SNAPSHOT-runner

  create-docker-image:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - restore_image_file
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run:
          command: ls -l
      - run:
          name: Build docker image
          command: |
            docker build -f src/main/docker/Dockerfile.native-image -t lcm-sayu build
      - run:
          name: Save image to an archive
          command: |
            mkdir docker-image
            docker save -o docker-image/image.tar lcm-sayu

workflows:
  version: 2
  buildjar-and-buildnative:
    jobs:
        - build
        - native:
            requires:
              - build
        - create-docker-image:
            requires:
              - native
