#
# Native Quarkus CircleCI configuration file
#
version: 2.1
commands:
  restore_repo:
    description: "Restore repo from cache"
    steps:
      - restore_cache:
          keys:
            - cache-repo
executors:
  graalvm-java11:
    docker:
      - image: oracle/graalvm-ce:20.2.0-java11
    working_directory: ~/repo
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx3200m
      TERM: dumb
jobs:
  build:
    executor: graalvm-java11
    steps:
      - restore_repo

      # Checkout the source code
      # ########################
      - checkout
      - save_cache:
          paths:
            - .
          key: cache-repo

      # Restore any files we may have cached
      # ########################
      - restore_cache:
          keys:
            - gradle-dependencies-native
      # Cache the maven dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-native

      - run:
          name: Build (jar)
          command: ./gradlew quarkusBuild

      - store_artifacts:
          path: build/libs/lcm-sayu-1.0.0-SNAPSHOT.jar

  native:
    executor: graalvm-java11
    steps:
      - restore_repo

      # Restore any files we may have cached
      # ########################
      - restore_cache:
          keys:
            - gradle-dependencies-native

      # Cache the maven dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-native

      # Install GraalVM and native-image, needed for a native Quarkus build
      # ########################
      - run:
          name: Install native-image
          command: gu install native-image

      # Perform a native Quarkus build and verify
      # ########################
      - run:
          name: Build (Native)
          command: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.additional-build-args=--static
          no_output_timeout: 30m
      - store_artifacts:
          path: build/lcm-sayu-1.0.0-SNAPSHOT-runner

workflows:
  version: 2
  buildjar-and-buildnative:
    jobs:
        - build
        - native:
            requires:
              - build
