version: "3.8"
services:
  web:
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_URL=postgres
      - DB_PORT=5432
      - DB_NAME=lcmsayudb
    image: lcm-sayu
    ports:
      - "80:80"
    depends_on:
      - postgres
  postgres:
    image: library/postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lcmsayudb
